# fly.toml app configuration file generated for autumn-wood-2386 on 2023-12-18T20:51:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-wood-2386"
primary_region = "atl"

[build]

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
